moysees/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
	url(r'^produto/', include('django.contrib.auth.urls')),
	url(r'^produto/', include('produto.urls', namespace="produto")),
    url(r'^admin/', include(admin.site.urls)),
]

produto/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^prioridade/$', views.priority, name='priority'),
]

produto/models.py
from __future__ import unicode_literals

from django.db import models

class Product(models.Model):
    name = models.CharField(max_length=500, blank=True, null=True)
    priority = models.BooleanField(default=False)

    def __str__(self):
    	return self.name

    class Meta:
        managed = True
        db_table = 'product'

produto/views.py
from django.shortcuts import render, render_to_response, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.template import RequestContext, loader
from .models import Product
from django.core.urlresolvers import reverse
from django.contrib.auth import views
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

# Create your views here.

def login(request):
    template_response = views.login(request)
    return template_response

@login_required(login_url='/login/')
def index(request):
	products = product_pagination(Product.objects.filter(priority=True), request.GET.get('page'))
	context = {'products': products}
	return render_to_response('produto/index.html', context, context_instance=RequestContext(request))

@login_required(login_url='/login/')
def priority(request):
	try:
		product = get_object_or_404(Product, pk=request.POST['product_id'])
		product.priority = True
		product.save()
	except (ValueError, Http404):
		products = product_pagination(Product.objects.filter(priority=True))
		context = {'message': "ID do Produto incorreto", 'products': products}
		return render_to_response('produto/index.html', context, context_instance=RequestContext(request))

	return HttpResponseRedirect(reverse('produto:index'))

def product_pagination(products, page=0):
	paginator = Paginator(products, 10) 

	try:
		products = paginator.page(page)
	except PageNotAnInteger:
		products = paginator.page(paginator.num_pages)
	except EmptyPage:
		products = paginator.page(paginator.num_pages)

	return products

produto/templates/produto/index.html
{% extends "base.html" %}

{% block head %} Produto Prioritários {% endblock %}

{% block content %}
<div class="row">
  <div class="col-md-12">
    <h1>Produtos Prioritários</h1>
  </div>
</div>
<div class="row">
  <div class="col-md-8">
    <form class="form-inline" action="{% url 'produto:priority' %}" method="post">
      {% csrf_token %}
      <div class="form-group">
        <label for="ID">ID do Produto: </label>
        <input name="product_id" type="text" class="form-control" id="ID" placeholder="Id do produto">
      </div>
      <input type="submit" class="btn btn-default" value="Marcar" />
    </form>
    {% if message %}
    <p class="text-danger">{{ message }}</p>
    {% endif %}
  </div>
</div>
<hr/>
<div class="row">
  {% if products %}
  <div class="col-md-12">
    <table class="table table-bordered ">
      <thead>
        <tr>
          <th>ID</th>
          <th>Produto</th>
          <th>Prioritário</th>
        </tr>
      </thead>
      <tbody>
        {% for product in products %}
        <tr>
          <td>{{ product.id }}</td>
          <td>{{ product.name }}</td>
          {% if product.priority = True %}
          <td>Sim</td>
          {% endif %}
          {% if product.priority = False %}
          <td>Não</td>
          {% endif %}
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>  
  {% endif %}
</div>
<div class="row">
    {% if products %}
    <div class="col-md-6">
      <nav>
        <ul class="pagination">
          {% if products.has_previous %}
          <li>
            <a href="?page={{ products.previous_page_number }}" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
            </a>
          </li>
          {% endif %}
          {% for page_range in products.paginator.page_range %}
          <li {% if products.number = page_range %} class="active" {% endif %}>
            <a href="?page={{ page_range }}">{{ page_range}} 
            {% if products.number = page_range %} 
            <span class="sr-only">(current)</span>
            {% endif %}
            </a></li>
          {% endfor %}
          {% if products.has_next %}
          <li>
            <a href="?page={{ products.next_page_number }}" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
            </a>
          </li>
          {% endif %}
        </ul>
      </nav>
    </div>
    {% endif %}
</div>  
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    
    <title>Moysees - {% block head %} {% endblock %}</title>
    

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'produto/signin.css' %}" />


    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <div class="container">
       {% block content %}{% endblock %}
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  </body>
</html>